kind: Deployment
apiVersion: apps/v1
metadata:
  name: covid-19-tracker-deployment
  namespace: covid-19-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: covid-19-tracker
  template:
    metadata:
      labels:
        app: covid-19-tracker
    spec:
      containers:
        - name: covid-19-tracker
          image: ncuxez/covid-19-tracker:1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              #name: http
              protocol: TCP