apiVersion: v1
kind: Service
metadata:
  name: covid-19-tracker-service
  labels:
    app: covid-19-tracker
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      nodePort: 31000
  selector:
    app: covid-19-tracker