export const SET_LOADING = 'SET_LOADING';
export const SET_CURRENT_COVID19_DATA = 'SET_CURRENT_COVID19_DATA';
export const SET_DAILY_COVID19_DATA = 'SET_DAILY_COVID19_DATA';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const SET_SELECTED_COUNTRY_DATA = 'SET_SELECTED_COUNTRY_DATA';
export const SET_GLOBAL_DATA = 'SET_GLOBAL_DATA';
